version: '3'

services:
  json-server:
   build: ./json-server
   container_name: test-json-server
   ports: 
    - '8080:8080'
   volumes:
    - ./json-server:/data
    - json-node-modules:/data/node_modules
   command:  sh -c 'npm run watch & json-server --p 8080 --watch merge.json --host 0.0.0.0'
  node:
    build: ./recommend-music
    volumes:
      - ./recommend-music:/usr/src/app
      - react-node-modules:/usr/src/app/node_modules
    command: sh -c 'npm run start'
    ports:
      - '3000:3000'

volumes:
  react-node-modules:
  json-node-modules: